<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="9.0.2" />
    <PackageReference Include="Dapper" Version="2.1.35" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebQueryTool.Domain\WebQueryTool.Domain.csproj" />
  </ItemGroup>

</Project>
